apiVersion: apps/v1
kind: Deployment
metadata:
  name: l4-deployment
  labels:
    app: l4-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: l4-frontend
  template:
    metadata:
      labels:
        app: l4-frontend
    spec:
      containers:
      - name: frontend-container
        image: ifilyaninitmo/itdt-contained-frontend:master
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_USERNAME
          value: Antsiferova
        - name: REACT_APP_COMPANY_NAME
          value: ITMO
